# Generated by Django 4.1.3 on 2022-12-01 15:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Carros",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        blank=True,
                        default=uuid.uuid4,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("nome", models.CharField(max_length=50)),
                ("marca", models.CharField(max_length=50)),
                ("modelo", models.CharField(max_length=50)),
                ("foto_url", models.CharField(max_length=80)),
                ("ano", models.IntegerField()),
                ("localizacao", models.CharField(max_length=80)),
                ("quilometragem", models.IntegerField()),
                (
                    "valor_original",
                    models.DecimalField(decimal_places=2, max_digits=20),
                ),
                (
                    "valor_promocional",
                    models.DecimalField(decimal_places=2, max_digits=20, null=True),
                ),
            ],
        ),
    ]
